---
title: "【1.3】自作の例外を定義する"
date: 2023-08-17T22:31:11+09:00
tags: [""]
seq: [""]
draft: false
---

- `Exception`から継承させた自作の例外を定義できる

```python
class MyBaseError(Exception)
    def __init__(self, code, msg) -> None:
        self.code = code
        self.msg = msg
    def __str__(self) -> str:
        return f"{self.code} {self.msg}"

class ParameterError(MyBaseError)
    def __init__(self, msg: str) -> None:
        super().__init__("errorCode", msg)

try:
    ...
except ValueError as e:
    raise ParameterError("ValueErrorによってエラーが出ました") from e
```